### ISSUE TITLE
Can't convert cuda tensor to numpy

### ISSUE THREAD

**Issue by luizapozzobon** [thanard/causal-infogan#3]
Hello!

When I tried to run the code, first I encountered a numpy bug (about not being able to find a function). I managed to make it work by upgrading it to version 1.16.2 with pytorch 0.2.0 and python 3.6. However, this is now the error I encounter when running the code, and can't seem to fix.
I'm new to PyTorch so it could be something easily fixable that i'm not being able to see.

Thanks!!

UniformDistribution()
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    trainer = Trainer(*var_list, **kwargs)
  File "/home/luiza/TCC/infogan/causal-infogan/trainer.py", line 74, in __init__
    self.eval_input = self._eval_noise()
  File "/home/luiza/TCC/infogan/causal-infogan/trainer.py", line 102, in _eval_noise
    vrange=self.P.unif_range)
  File "/home/luiza/TCC/infogan/causal-infogan/utils.py", line 96, in plot_img
    vmax=vrange[1], cmap='gray', aspect='auto')
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 2701, in imshow
    None else {}), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_axes.py", line 5494, in imshow
    im.set_data(X)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 638, in set_data
    self._A = cbook.safe_masked_invalid(A, copy=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/__init__.py", line 784, in safe_masked_invalid
    x = np.array(x, subok=True, copy=copy)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 450, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by luizapozzobon** [comment]
Was able to fix it by changing line 100 from trainer.py to
plot_img(c.t().data.cpu().numpy(),
